id: P004508
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18556
  title: ཆ་བྱད་དཔྱད། བཅོས་སྒྲིག་མ།
  author: ''
  volumes:
    e224001eb4a1497fab5cba3b1f164622:
      image_group_id: I8LS18558
      title: ''
      volume_number: 1
      total_pages: 295
      base_file: v001.txt
